# Generated by Django 4.1.3 on 2022-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='mail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
