# Generated by Django 4.1.3 on 2022-12-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_profile_user_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_user',
            name='mail',
        ),
    ]
