# Generated by Django 4.1.3 on 2023-01-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_contact_list_of_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_contact',
            name='image_contact',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
