# Generated by Django 4.1.3 on 2023-01-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_list_of_contact_image_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_of_contact',
            old_name='mail',
            new_name='email',
        ),
    ]
